apiVersion: v1
kind: Service
metadata:
  namespace: tu2k22
  name: zhiyuan-django
  labels:
    app: zhiyuan-django
spec:
  type: NodePort
  selector:
    app: zhiyuan-django
  ports:
    - port: 8080
      targetPort: 8080
